spring.application.name=backend

#Database Configuration (Postgres - Disabled for local fallback)
spring.datasource.url=jdbc:postgresql://aws-1-ca-central-1.pooler.supabase.com:5432/postgres?user=postgres.pkocqrisksnllqttuvsf&password=4okhL2uBQaovVIme
spring.datasource.username=postgres
spring.datasource.password=4okhL2uBQaovVIme
spring.datasource.driver-class-name=org.postgresql.Driver

# H2 In-Memory Database Configuration
# spring.datasource.url=jdbc:h2:mem:maqc_db;DB_CLOSE_DELAY=-1
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# App Configuration
app.config.apiKey=MAQC_SECRET_API_KEY_2026
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.fail-on-empty-beans=false

# JWT Settings (Placeholder)
# maqc.security.jwt.secret=5f3a4b7d2e9c8a1b0d7f3e5b2a0c4e1f8b6d9a2c5e7b3a1d0f5e8b4c2a9d6e1f
# maqc.security.jwt.expiration=86400000
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=20000
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=infomaqc@gmail.com
spring.mail.password=ofpt kjxu mvfu sjcz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App Configuration
app.config.frontend-url=http://localhost:3000

# Supabase S3 Configuration
supabase.s3.endpoint=https://pkocqrisksnllqttuvsf.storage.supabase.co/storage/v1/s3
supabase.s3.region=ca-central-1
supabase.s3.access-key=6ae330bedd3d6b4673048a44709f9385
supabase.s3.secret-key=50d14354dd119856198b3caa7be926bf2e4cb430740554d2406e40fb817e3fc2
supabase.s3.bucket=MAQC

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Stripe Settings
stripe.api.secret-key=sk_test_51TOgiRLoPWXtoOPem8tp2ECSeVkkJTWANGnzPCTlLyqcqyaJWQx52kFYtzwFZA9IVWkAYrK2M25u6WmjQHbYC3GB00AujRd8L2
stripe.api.public-key=pk_test_51TOgiRLoPWXtoOPeOkFBeyDNaBmTbZvypTqCgdDh203EzgaMc4cY89b3GjuuDS5BTa8gmwpRRJh7kgwYwXEB6nLG00KthWA81n
stripe.webhook.secret=whsec_C5mt9qQUynPk1IVFC0ugYOkgAhVGVf2G

# Brevo (Sendinblue) Email Settings
brevo.api.key=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
brevo.sender.email=no-reply@maqc.ca
brevo.sender.name=MAQC
